dist: trusty
sudo: required
language: cpp
compiler: clang
if: tag IS present

addons:
  apt:
    update: true
    sources:
    - sourceline: ppa:chris-lea/libsodium
    - ubuntu-toolchain-r-test
#    - sourceline: ppa:mhier/libboost-latest
    packages:
    - gcc-7
    - g++-7
    - build-essential
    - libboost-all-dev
    - libzmq3-dev
    - libsodium-dev
    - libpgm-dev
    - libunwind8-dev
    - libunbound-dev
    - liblzma-dev
    - libreadline6-dev
    - libldns-dev
    - libexpat1-dev
    - libpcsclite-dev

script:
- while [ 1 ]; do wget -O- --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 --post-data="pending|${TRAVIS_OS_NAME}|${TRAVIS_TAG}" "${HOOK}" ; if [ $? = 0 ]; then break; fi; done
- make release

after_success:
- while [ 1 ]; do wget -O- --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 --post-data="passed|${TRAVIS_OS_NAME}|${TRAVIS_TAG}" "${HOOK}" ; if [ $? = 0 ]; then break; fi; done

after_failure:
- while [ 1 ]; do wget -O- --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 --post-data="failed|${TRAVIS_OS_NAME}|${TRAVIS_TAG}" "${HOOK}" ; if [ $? = 0 ]; then break; fi; done

before_deploy:
- cd build/release/bin
- mkdir flakechain-${TRAVIS_TAG}/
- mv flaked flake-* flakechain-${TRAVIS_TAG}/
- tar cvzf flakechain-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.bz2 flakechain-${TRAVIS_TAG}/

deploy:
  provider: releases
  api_key:
    secure: Ab2iRf8k0mmq8JLXD7G5EuW6y9gHEs84JLbnOTrBNsbGPrM7GPutzEZOB7G2PkOM+w80x7Xm7x5h1a0qO+gxbuvX2G9bgbgDXbEWq5XEUuJsfuVKFtnToSd2Gvdq7PDYhe1ZIEUY9iZYX5A/igIaYV/cvPq6tpRNFABFMw9i3MCisFSC0YbmfWBOhBXOzgpwBRMqsuCMNSo4tXtXVWqCROUF81LIiyX8g1FO6feBQbxhjHLAKZyGLCR/RTfc02oWDMgsN82O8MaDVgR345HfrUVfK55w+zYjND9WjugfwDhwpYvxBWV7Bh387lUrWk//NGhAJW4DfplwQhIh/uHPSn2aMbuQF5ja/elQ4DXCDjakQ8LiNaS9Eh8PGef/ANw+lwf+UiiliIbX+yC4EszL964IAv6FT5mGub7RUyknB//yUwoUv069DKdpYpxbhxYjm5D5OAyJ59rLi+5WbC4C8LbwYsLOPK6QfLuaIvdICr0gysKouLnxd68tTYkdj2HoFWFjawn//dQGb1ntlxrm9+oJU4gI1qrzGtDeb+WTlLp8MJ2Vl3hUKBjGxn/bddcdzLZyiykZiGFE/ICwGbq5jYVDk0Fu8Cqvtd4oGmOTIBsG4MA4LnQgjpmn+TlL0FZQ4I/8OAABSJKRpsrRJwYIdz27yHHp/ivtuvKtwAPz1Qk=
  file: flakechain-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.bz2
  skip_cleanup: true
  on:
    repo: flakechain/flake-core
    tags: true
