language: cpp
os: linux
dist: trusty
sudo: false

matrix:
  include:
  - env: COMPILER=g++ BUILD=Release STANDARD=14
    compiler: gcc
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        packages:
        - g++
        - boost1.67
        - libzmq3-dev

script:
- make