sudo: false
language: cpp

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost1.67-all-dev
    env:
    - MATRIX_EVAL="CC=gcc && CXX=g++"
    - LABEL="linux"
    - STRIP="strip"

before_install:
- eval $MATRIX_EVAL

script:
- make