language: cpp
os: linux
dist: trusty
sudo: false

matrix:
  include:
  - env: COMPILER=g++ BUILD=Release STANDARD=14
    compiler: gcc
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        packages:
        - build-essential
        - boost1.67
        - libzmq3-dev
        - libsodium-dev
        - libpgm-dev
        - libunwind8-dev
        - libunbound-dev
        - liblzma-dev
        - libreadline6-dev
        - libldns-dev
        - libexpat1-dev
        - libpcsclite-dev

script:
- make