language: cpp
os: linux
dist: trusty
sudo: false

matrix:
  include:
  - env: COMPILER=g++-6 BUILD=Release STANDARD=14
    compiler: gcc
    addons:
      apt:
        update: true
        sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - boost1.67

script:
- make