image: Visual Studio 2017
version: 0.4.0-alpha.{build}
platform: x64
clone_folder: c:\Projects\flake-core

branches:
    only:
        - master
        
configuration: Debug

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-17

install:
- git submodule update --init --recursive

build_script:
- echo "Starting build"
- md build
- cd build
- cmake -G "Visual Studio 17 Win64" ..
- echo "dir .."
- dir ..
- echo "dir ."
- dir
- echo "MSBuild call"
- MSBuild flake-core.sln /p:Configuration=Release /m

after_build:
- cd src\Release
- mkdir flakechain-%APPVEYOR_BUILD_NUMBER%
- copy *.exe flakechain-%APPVEYOR_BUILD_NUMBER%
- 7z a flakechain-%APPVEYOR_BUILD_NUMBER%-windows.zip flakechain-%APPVEYOR_BUILD_NUMBER%

artifacts:
- path: flakechain-%APPVEYOR_BUILD_NUMBER%-windows.zip
  name: FlakechainRelease
