image: Visual Studio 2013
version: 0.4.9-alpha.{build}
platform: x64
clone_folder: c:\Projects\flake-core

branches:
    only:
        - master
        
configuration: Debug

environment:
  BOOST_ROOT: C:\Libraries\boost_1_58_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_58_0\lib64-msvc-13

install:
- git submodule update --init --recursive

  BOOST_ROOT  C:\Libraries\boost_1_58_0
  BOOST_LIBRARYDIR  C:\Libraries\boost_1_58_0\lib64-msvc-13.1
  VCPKG_DIR C:\Tools\vcpkg
  PLATFORM  x64

init:
  cd %VCPKG_DIR%
  git pull
  echo.set(VCPKG_BUILD_TYPE release)>> %VCPKG_DIR%\triplets\%PLATFORM%-windows.cmake
  .\bootstrap-vcpkg.bat
  vcpkg version
  cd %APPVEYOR_BUILD_FOLDER%

install:
  git submodule update --init --recursive

  vcpkg install boost-system boost-filesystem boost-thread boost-date-time boost-chrono boost-regex boost-serialization boost-program-options boost-locale zeromq cppzmq libsodium --triplet %PLATFORM%-windows

  vcpkg list

  set PATH=%VCPKG_DIR%\installed\%PLATFORM%-windows\bin;%PATH%

build_script:
- echo "Starting build"
- md build
- cd build
- cmake -G "Visual Studio 13 Win64" ..
- echo "dir .."
- dir ..
- echo "dir ."
- dir
- echo "MSBuild call"
- MSBuild flake-core.sln /p:Configuration=Release /m

after_build:
- cd src\Release
- mkdir flakechain-%APPVEYOR_BUILD_NUMBER%
- copy *.exe flakechain-%APPVEYOR_BUILD_NUMBER%
- 7z a flakechain-%APPVEYOR_BUILD_NUMBER%-windows.zip flakechain-%APPVEYOR_BUILD_NUMBER%

artifacts:
- path: flakechain-%APPVEYOR_BUILD_NUMBER%-windows.zip
  name: FlakechainRelease
